### PR TITLE
Fixed emphasis editor and added some tooltips

### LINKED ISSUE #40: Layout emphasis per direction

### PR DESCRIPTION
**Pull request by villejuutila**
Resolves #40

### CODE REVIEW

File: src/components/layout/v2/alignment-editor-html.tsx [hunk 1]
```diff
@@ -27,14 +28,42 @@ type AlignmentIconRow = {
...
-const AlignmentEditorHtml = ({ onChange }: Props) => {
-  const [selected, setSelected] = useState<LayoutAlignment>();
+const AlignmentEditorHtml = ({ onChange, element }: Props) => {
+  const ALIGNMENT_MAP = HtmlComponentsUtils.ALIGNMENT_MAP;
+  /**
+   * Gets the alignment direction for the component
+   */
+  const getAlignmentDirection = () => element.style.flexDirection ?? "row";
+
+  const getSelectedAlignment = () => {
```
Comment (jarinykanen) [inline src/components/layout/v2/alignment-editor-html.tsx:44]: Should this have ts docs?

**Review by jarinykanen — APPROVED** [review]

File: src/components/layout/v2/alignment-editor-html.tsx (hunk 1 above)
Comment (villejuutila) [reply src/components/layout/v2/alignment-editor-html.tsx:49]: Resolved
